# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=8eaa6f6421
# 
# 

# ********RoostGPT********
Feature: Test /aisp/accounts/{accountId}/transactions API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = {Authorization: '#(AUTH_TOKEN)', 'x-fapi-auth-date': '#(new Date().toISOString())', 'x-fapi-customer-ip-address': '192.168.1.1', 'x-fapi-interaction-id': 'E2E_XYZ', 'Accept-Language': 'en-US'}

  Scenario Outline: Test GET /aisp/accounts/{accountId}/transactions API with valid inputs
    Given path 'aisp/accounts', '<accountId>', 'transactions'
    And params {fromDate: '<fromDate>', toDate: '<toDate>'}
    And headers headers
    When method get
    Then status 200
    And match response.data == '#object'
    And match response.data.transaction == '#array'
    And match response.data.transaction[0] == '#object'
    And match response.links == '#object'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_transactions_get.csv') |
