# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts_get for http method type GET 
# RoostTestHash=1174086886
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = {Authorization: '#('Bearer ' + authToken)', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': 'randomString', 'Accept-Language': 'en-US'}

  Scenario: Test /aisp/accounts endpoint with valid parameters
    Given path '/aisp/accounts'
    When method get
    Then status 200
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
    * def account = response.data.account[0]
    And match account == '#array'
    And match account.accountId == '#string'
    And match account.accountNumber == '#string'
    And match account.accountType == '#string'
    And match account.accountSubType == '#string'
    And match account.productName == '#string'
    And match account.accountStatus == '#string'
    And match account.currency == '#string'
    * def links = response.data.links
    And match links.self == '#string'
    And match links.prev == '#string'
    And match links.next == '#string'

  Scenario: Test /aisp/accounts endpoint with invalid parameters
    Given path '/aisp/accounts'
    When method get
    Then status 400
    And match responseHeaders['Content-Type'] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
    * def error = response.errors[0]
    And match error.id == '#string'
    And match error.code == '#string'
    And match error.causes == '#string'
    And match error.extendedDetails.path == '#string'
