# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/availability_post for http method type POST 
# RoostTestHash=f477236dc8
# 
# 

# ********RoostGPT********
Feature: Test aisp accounts availability API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authHeader = { 'Authorization': '#(authToken)', 'Content-Type': 'application/json' }

  Scenario Outline: Verify the aisp accounts availability API
    Given path '/aisp/accounts/availability'
    And headers authHeader
    And request
      """
      <requestBody>
      """
    When method post
    Then status <statusCode>
    And match response ==
      """
      <expectedResponse>
      """

    Examples:
      | read('aisp_accounts_availability_post.csv') |
