# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=8067523cbb
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints - Account Status by Account ID

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Validate account status by account ID
    Given path '/aisp/accounts/', '<accountId>'
    And header Authorization = authToken
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status <status_code>
    And match responseHeaders['Content-Type'][0] == '<Content-Type>'
    And match responseHeaders['x-fapi-interaction-id'][0] == '<x-fapi-interaction-id>'
    And match $response.data.account[*].accountId == '#string'
    And match $response.data.account[*].accountNumber == '#string'
    And match $response.data.account[*].accountType == '#string'
    And match $response.data.account[*].accountSubType == '#string'
    And match $response.data.account[*].productName == '#string'
    And match $response.data.account[*].accountStatus == '#string'
    And match $response.data.account[*].currency == '#string'
    And match $response.links.self == '#string'
    And match $response.links.prev == '#string'
    And match $response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_get.csv') |
