# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8deb268cea
# 
# 

# ********RoostGPT********
Feature: Account Consents API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Validate GET /aisp/account-consents/{consentId} endpoint
    Given path 'aisp/account-consents/', '<consentId>'
    And header Authorization = AUTH_TOKEN
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status <status_code>
    And match response.data.consentId == '<consentId>'
    And match response.data.creationDate == '#string'
    And match response.data.status == '#string'
    And match response.data.statusUpdateDate == '#string'
    And match response.data.permissions == '#[]'
    And match response.data.permissions[0] == '#string'
    And match response.data.expirationDate == '#string'
    And match response.data.transactionFromDate == '#string'
    And match response.data.transactionToDate == '#string'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'
    And match response.headers['x-fapi-interaction-id'] == '#string'

    Examples:
      | read('aisp_account-consents_consentId_get.csv') |
