# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /aisp/accounts/{accountId}/balances_get for http method type GET 
# RoostTestHash=0095e68c59
# 
# 

# ********RoostGPT********
Feature: Test Fulfilment endpoints

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']

  Scenario Outline: Test balancesByAccount endpoint with valid input
    Given path '/aisp/accounts/', '<accountId>', '/balances'
    And header Authorization = 'Bearer ' + AUTH_TOKEN
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method get
    Then status 200
    And match response.data.account[*].accountId == '#string'
    And match response.data.account[*].balance[*].type == '#string'
    And match response.data.account[*].balance[*].creditDebitIndicator == '#string'
    And match response.data.account[*].balance[*].amount == '#string'
    And match response.data.account[*].balance[*].currency == '#string'
    And match response.data.account[*].balance[*].datetime == '#string'
    And match response.links.self == '#string'
    And match response.links.prev == '#string'
    And match response.links.next == '#string'

    Examples:
      | read('aisp_accounts_accountId_balances_get.csv') |
