# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=6bbed7894a
# 
# 

# ********RoostGPT********
Feature: Events API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#(authToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'date', 'x-fapi-customer-ip-address': 'ip', 'x-fapi-interaction-id': 'interaction_id', 'Accept-Language': 'language' }

  Scenario Outline: Test POST /events endpoint
    Given path '/events'
    And headers headers
    And request { "ack": "<ack>", "returnImmediately": "<returnImmediately>", "maxEvents": "<maxEvents>" }
    When method post
    Then status <status_code>
    And match response == <response_body>
    And match responseHeaders == <response_headers>

    Examples:
      | read('events_post.csv') |
