# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/balances_get for http method type GET 
# RoostTestHash=a9aeb5e089
# 
# 

# ********RoostGPT********
@ignore
Feature: Accounts API - aisp/accounts/{accountId}/balances

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * configure headers = { 'Authorization': '#(bearerAuthToken)', 'x-fapi-auth-date': '#(authDate)', 'x-fapi-customer-ip-address': '#(customerIpAddress)', 'x-fapi-interaction-id': '#(interactionId)', 'Accept-Language': '#(acceptLanguage)' }

Scenario Outline: Get account balances by account ID
  Given path 'aisp','accounts', '<accountId>', 'balances'
  When method get
  Then status 200
  And match responseHeaders['Content-Type'] == 'application/json'
  And match response.data.account.size() == response.data.account.size()
  And match each response.data.account contains { accountId: '#string', balance: '#array' }

Examples:
  | accountId            | bearerAuthToken                      | authDate               | customerIpAddress | interactionId | acceptLanguage |
  | 'ThR-RpLMV5lZzDu8vrfEFg' | 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | 'someId' | 'en-HK' |  

Scenario Outline: Get account balances by invalid account ID
  Given path 'aisp','accounts','<accountId>', 'balances'
  When method get
  Then status 400
  And match responseHeaders['Content-Type'] == 'application/json'
  And match response contains { code: '#string', message: '#string', errors: '#array' }

Examples:
  | accountId | bearerAuthToken | authDate              | customerIpAddress | interactionId | acceptLanguage |
  | '' | 'Bearer KjKDbKGDVcB-qopwk8CaH5vrEfg' | 'Sun, 10 Sep 2017 21:45:31 UTC' | '169.250.150.250' | 'invalidId' | 'zh-HK' | 
