# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=0ca716f7be
# 
# 

# ********RoostGPT********
Feature: Test /aisp/account-consents endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/aisp/account-consents'

  Scenario Outline: Test consent-setup operation with Post method
    Given path '/'
    And header Authorization = 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'
    And header Content-Type = 'application/json'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = '<interactionId>'
    And header Accept-Language = '<language>'
    And request { "data": '<data>' }
    When method post
    Then status <statusCode>

    Examples:
      | read('aisp_account-consents_post.csv') |
