# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8f01df3f76
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#('Bearer ' + AUTH_TOKEN)', 'x-fapi-auth-date':'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address':'169.254.169.254', 'x-fapi-interaction-id': 'any-unique-str', 'Accept-Language':'en-HK' }

  Scenario Outline: Testing GET /aisp/account-consents/{consentId} endpoint with valid input parameters
    Given path 'aisp', 'account-consents', '<consentId>'
    And headers headers
    When method get
    Then status 200
    And match responseHeaders['x-fapi-interaction-id'] == 'any-unique-str'
    And match response.data.consentId == '<consentId>'
    And match response.data.creationDate == '#string'
    And match response.data.status == '#string'
    And match response.data.status == oneOf('PendingAuthorise', 'Rejected', 'Authorised', 'Revoked')
    And match response.data.statusUpdateDate == '#string'
    And match response.data.permissions contains ['#string']
    And match response.data.expirationDate == '#string'
    And match response.data.transactionFromDate == '#string'
    And match response.data.transactionToDate == '#string'

    Examples:
      | read('aisp_account-consents_consentId_get.csv') |
