# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=1645afe2f7
# 
# 

# ********RoostGPT********
Feature: Aisp Account Analysis

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * configure headers = { "Authorization" : "Bearer "+authToken }

Scenario Outline: Verify account status with different account ids
  Given path "/aisp/accounts/<accountId>"
  And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
  And header x-fapi-customer-ip-address = '169.254.169.254'
  And header Accept-Language = 'en-HK'
  When method GET
  Then status 200
  And match response.data.account contains { "accountId" : "#(accountId)" }
  * def accountNumber = response.data.account[0].accountNumber
  Then match response.data.account[0] == { "accountId": "#(accountId)", "accountNumber": "#(accountNumber)", "accountType": "#string", "accountSubType": "#string", "productName": "#string", "accountStatus": "#string", "currency": "#string"  }

Examples: 
  | accountId                           |
  | 'ThR-RpLMV5lZzDu8vrfEFg'            |
  | 'j6Nava8pWVdRzKu79rvFEh'            |
