# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=9805a5f309
# 
# 

# ********RoostGPT********
Feature: Testing transactionsByAccount

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Valid transactions scenarios
    Given path 'aisp/accounts/', '<accountId>', '/transactions'
    And header Authorization = '<authHeader>'
    And header x-fapi-auth-date = '<authDate>',
    And header x-fapi-customer-ip-address = '<ipAddress>',
    And header x-fapi-interaction-id = '<interactionId>',
    And header Accept-Language = '<language>',
    And param fromDate = '<fromDate>',
    And param toDate = '<toDate>'
    When method get
    Then status 200
    And match response.data.transaction contains {accountId: '#string', accountNumber: '#string', transactionDescription: '#string', transactionDate: '#string', creditDebitIndicator: '#string', status: '#string', amount: '#string', currency: '#string'}

    Examples:
      | read('aisp_accounts_accountId_transactions_get.csv') |

  Scenario Outline: Invalid transactions scenarios
    Given path 'aisp/accounts/', '<accountId>', '/transactions'
    And header Authorization = '<authHeader>'
    And header x-fapi-auth-date = '<authDate>',
    And header x-fapi-customer-ip-address = '<ipAddress>',
    And header x-fapi-interaction-id = '<interactionId>',
    And header Accept-Language = '<language>',
    And param fromDate = '<fromDate>',
    And param toDate = '<toDate>'
    When method get
    Then status 400

    Examples:
      | accountId   | authHeader        | authDate | ipAddress | interactionId | language | fromDate | toDate    |
      | 'invalidId' | 'wrongAuthBearer' | ''       | ''        | ''            | 'en-US'  | ''       | '2017-10' |
