# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8f01df3f76
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup

Background: 
    * def authHeaderValue = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase

Scenario Outline: Consent retrieval

    Given path '/aisp/account-consents/', '<consentId>'
    And header Authorization = authHeaderValue
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'randomString'
    And header Accept-Language = 'en-HK'
    When method get
    Then status 200
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
    And match response == """ {data: '#object', links: '#object'} """
    And match response.data == """ {consentId: '<consentId>', creationDate: '#string', status: '#string', statusUpdateDate: '#string', permissions: '#[]'} """
    And match response.data.permissions contains only ['ReadAccountAvailability','ReadAccountStatus','ReadAccountBalance','ReadAccountTransaction']

    Examples:
     | consentId                                  |
     | '7404e99b-1a4d-4b08-b441-c327661527f0'    |
