# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_delete for http method type DELETE 
# RoostTestHash=460872f4ab
# 
# 

# ********RoostGPT********
Feature: AISP account consent deletion

Background: 
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': '', 'Accept-Language': 'en-HK' }

Scenario Outline: Delete consent record
    Given path '/aisp/account-consents/', '<consentId>'
    When method delete
    Then match responseStatus == <expectedStatusCode>
    And match responseHeaders['x-fapi-interaction-id'] == '#string'
Examples:
|consentId                             |expectedStatusCode|
|'7404e99b-1a4d-4b08-b441-c327661527f0'|204               |
|'invalidConsentId'                    |400               |

