# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/availability_post for http method type POST 
# RoostTestHash=71c7c56f2c
# 
# 

# ********RoostGPT********
Feature: Test the Account Availability API endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = {Authorization: '#(authToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': '', 'Accept-Language': 'en-HK'}
  * configure headers = headers

Scenario Outline: Testing the Account Availability API with valid input payloads

  Given path '/aisp/accounts/availability'
  And request {"data": [{"paramName": "<paramName>", "paramValue": "<paramValue>"}]}
  When method post
  Then status 200
  And match response contains {"data": [{ "paramName": "<paramName>", "status": "<status>"}]}

  Examples:
    | paramName   | paramValue | status |
    | accountType |  Personal  | Yes    |

Scenario Outline: Validate the error response when required header is missing

  Given path '/aisp/accounts/availability'
  And remove headers['<headerName>']
  And request {"data": [{"paramName": "<paramName>", "paramValue": "<paramValue>"}]}
  When method post
  Then status <statusCode>
  
  Examples:
    | headerName  | statusCode |
    | Content-Type | 415       |
    | Authorization | 401      |

Scenario Outline: Validate the error response when required field in request body is missing

  Given path '/aisp/accounts/availability'
  And request {"data": [{"paramName": "<paramName>"}]}
  When method post
  Then status <statusCode>
  
  Examples:
    | paramName  | statusCode |
    | accountType | 400      |
