# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_delete for http method type DELETE 
# RoostTestHash=460872f4ab
# 
# 

# ********RoostGPT********
Feature: Account Consent Deletion

Background: 
    * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Delete Account Consent
    Given path 'aisp/account-consents/', '<consentId>'
    And configure headers = { Authorization: ('Bearer ' + authToken), 'x-fapi-auth-date': '<x-fapi-auth-date>', 'x-fapi-customer-ip-address': '<x-fapi-customer-ip-address>', 'x-fapi-interaction-id': '<x-fapi-interaction-id>', 'Accept-Language': '<Accept-Language>'}
    When method delete
    Then status 204
    And match responseHeaders['x-fapi-interaction-id'] == '<x-fapi-interaction-id>'

Examples:
   | consentId                              | x-fapi-auth-date        | x-fapi-customer-ip-address | x-fapi-interaction-id | Accept-Language |
  | '7404e99b-1a4d-4b08-b441-c327661527f0' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | '12345'     | 'en-HK'   |
