# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/availability_post for http method type POST 
# RoostTestHash=71c7c56f2c
# 
# 

# ********RoostGPT********
Feature: Account Availability API tests

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Check API Response for different <paramName> values with Accept-Language <Accept-Language>

    Given path '/aisp/accounts/availability'
    And header Authorization = 'Bearer {{$processEnvironment.AUTH_TOKEN}}'
    And header Content-Type = 'application/json'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = '#uuid'
    And header Accept-Language = '<Accept-Language>'
    And request 
    """
      { 
      "data" : 
        [ 
          {
          "paramName" : "<paramName>",
          "paramValue" : "<paramValue>"
          } 
        ] 
      }
    """
    When method post
    Then status 200
    And match response.data[*].paramName contains '<paramName>'
    And match response.data[*].status contains '<status>'

    Examples: 
      | Accept-Language | paramName               | paramValue   | status |
      | "en-HK"         | "hkid"                  | "accountType"| "Yes"  |
      | "zh-HK"         | "travelDocumentNumber"  | "Personal"   | "No"   |
      | "zh-CN"         | "firstname"             | "accountType"| "Retry"|
