# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/balances_get for http method type GET 
# RoostTestHash=a9aeb5e089
# 
# 

# ********RoostGPT********
Feature: Test /aisp/accounts/{accountId}/balances endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Test GET /aisp/accounts/{accountId}/balances
    Given path 'aisp', 'accounts', '<accountId>', 'balances'
    And header Authorization = 'Bearer ' + karate.properties['AUTH_TOKEN']
    And header x-fapi-auth-date = '<x-fapi-auth-date>'
    And header x-fapi-customer-ip-address = '<x-fapi-customer-ip-address>'
    And header x-fapi-interaction-id = '<x-fapi-interaction-id>'
    And header Accept-Language = '<Accept-Language>'
    When method GET
    Then status <statusCode>

Examples:
  |   accountId       |   x-fapi-auth-date      |   x-fapi-customer-ip-address  |   x-fapi-interaction-id   |    Accept-Language  |  statusCode   |
  | 'ThR-RpLMV5lZzDu8vrfEFg'  |  'Sun, 10 Sep 2017 19:43:31 UTC'  |  '169.254.169.254' |  'unique-uuid'  | 'en-HK'  | 200  |
