# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=0ca716f7be
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
     
  Scenario Outline: Test POST request consent-setup endpoint
    Given path '/aisp/account-consents'
    And header Authorization = 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'
    And header Content-Type = 'application/json'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header x-fapi-interaction-id = 'uniqueId'
    And header Accept-Language = 'en-HK'
    And request read('request.json')
    When method post
    Then status 201 
    And match response == {data: '#object'}
    And match response.data == {consentId: '#string', creationDate: '#string', status: '#string', statusUpdateDate: '#string', permissions: '#array', expirationDate: '#string', transactionFromDate: '#string', transactionToDate: '#string'}      
  Examples:
    | permissions                                                                                 |
    | ['ReadAccountAvailability','ReadAccountStatus','ReadAccountBalance','ReadAccountTransaction']|
