# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents_post for http method type POST 
# RoostTestHash=0ca716f7be
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def AuthToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Validate request and responses for creating account consent setup

    Given path '/aisp/account-consents'
    And header Authorization = 'Bearer ' + AuthToken
    And header Content-Type = 'application/json'
    And header x-fapi-auth-date = 'Sun, 10 Sep 2017 19:43:31 UTC'
    And header x-fapi-customer-ip-address = '169.254.169.254'
    And header Accept-Language = 'en-HK'
    And request <requestBody>

    When method post

    Then match responseStatus == <responseCode>
    And match responseHeaders['Content-Type'][0] == 'application/json'
    And match responseHeaders['x-fapi-interaction-id'] != null
    And match response.data.consentId != null

    Examples:
      | requestBody                                                                                                                                                                                                      | responseCode |
      | { "data": { "permissions": ["ReadAccountAvailability"], "expirationDate": "2023-04-05T10:43:07+00:00", "transactionFromDate": "2023-04-05T10:43:07+00:00", "transactionToDate": "2023-04-05T10:43:07+00:00" } } | 201           |
      | { "data": { "permissions": ["ReadAccountStatus"], "expirationDate": "2023-04-05T10:43:07+00:00", "transactionFromDate": "2023-04-05T10:43:07+00:00", "transactionToDate": "2023-04-05T10:43:07+00:00" } }      | 201           |
