# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=9805a5f309
# 
# 

# ********RoostGPT********
Feature: Testing endpoint for retrieving transactions by account

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    
Scenario Outline: Validate transactions by account response for valid account
    Given path '/aisp/accounts/{accountId}/transactions'
    And headers {Authorization: '#(karate.properties['AUTH_TOKEN'])', 'x-fapi-auth-date':'#(fromDate)', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': 'random', 'Accept-Language': 'en-HK'}
    When method get
    Then status 200
    And match $ == '''{data: '#object'}'''
    And match data.transaction[*].accountId == '#string'
    And match data.transaction[*].accountNumber == '#string'
    And match data.transaction[*].transactionDescription == '#string'
    And match data.transaction[*].transactionDate == '#string'
    And data.transaction[*].creditDebitIndicator == ['Credit','Debit']
    And data.transaction[*].status == ['Booked','Pending']
    And match data.transaction[*].amount == '#string'
    And match data.transaction[*].currency == '#string'
    
Examples:
    | accountId | fromDate                     |
    | 'acc1'    | 'Sun, 10 Sep 2017 19:43:31 UTC' |
    | 'acc2'    | 'Sun, 10 Sep 2017 19:43:31 UTC' |
