# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/transactions_get for http method type GET 
# RoostTestHash=9805a5f309
# 
# 

# ********RoostGPT********
Feature: Account Transactions API Testing
  Carry out testing for /aisp/accounts/{accountId}/transactions API. The tests will consist of both valid and invalid requests. 

Background: Define and Set the API's Base URL
  * def urlBase = karate.properties['url.base'] || var urlBase = config.urlBase || 'http://localhost:8080'
  * url urlBase

Scenario Outline: Test Valid Authorization and Account Transactions Request  
  Given path 'aisp/accounts', '<accountId>', 'transactions'  
  And headers {Authorization: '#(authToken)', 'x-fapi-auth-date': '#(authDate)', 'x-fapi-customer-ip-address': '#(ipAddress)', 'x-fapi-interaction-id': '#(interactionId)', 'Accept-Language': '#(language)'}  
  And param fromDate = '<fromDate>'  
  And param toDate = '<toDate>'  
  When method get  
  Then status 200  
  And match response.data.transaction contains {accountId: '#(accountId)', creditDebitIndicator: '#(creditDebitIndicator)', status: '#(status)', amount: '#(amount)', currency: '#(currency)'}
  
  Examples:
  | authToken             | authDate                 | ipAddress       | interactionId | language | accountId         | fromDate  | toDate    | creditDebitIndicator | status  | amount | currency |
  | 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | '12345' | 'en-HK' | 'ThR-RpLMV5lZzDu8vrfEFg' | '2017-10-22' | '2017-10-23' | 'Credit' | 'Booked' | '20.00'  | 'USD'  |

Scenario Outline: Test Invalid Authorization
  Given path '/aisp/accounts', '<accountId>', 'transactions'
  And headers {Authorization: '#(authToken)', 'x-fapi-auth-date': '#(authDate)', 'x-fapi-customer-ip-address': '#(ipAddress)', 'x-fapi-interaction-id': '#(interactionId)', 'Accept-Language': '#(language)'}
  And param fromDate = '<fromDate>'
  And param toDate = '<toDate>'
  When method get
  Then status 401

  Examples:
  | authToken             | authDate                 | ipAddress       | interactionId | language | accountId         | fromDate  | toDate    |
  | 'InvalidAuthToken' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '169.254.169.254' | '12345' | 'en-HK' | 'ThR-RpLMV5lZzDu8vrfEFg' | '2017-10-22' | '2017-10-23' |
