# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}/balances_get for http method type GET 
# RoostTestHash=a9aeb5e089
# 
# 

# ********RoostGPT********
Feature: Fulfilment endpoints of API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * header Authorization = karate.properties['AUTH_TOKEN']
    * def headers = { 'x-fapi-auth-date': '#(authDate)', 'x-fapi-customer-ip-address': '#(ipAddress)', 'x-fapi-interaction-id': '#(interactionId)', 'Accept-Language': '#(language)' }

  Scenario Outline: Verify balances by account for valid inputs
    Given path '/aisp/accounts/{accountId}/balances'
    * replace 'accountId': '<accountId>'
    And headers = headers
    When method get
    Then status 200
    And match response.data.account contains { accountId: '<accountId>' }

    Examples:
      | read('aisp_accounts_accountId_balances_get.csv') |

  Scenario Outline: Verify error responses for invalid inputs
    Given path '/aisp/accounts/{accountId}/balances'
    * replace 'accountId': '<accountId>'
    And headers = headers
    When method get
    Then status <statusCode>

    Examples:
      | read('aisp_accounts_accountId_balances_get.csv') |
