# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=1645afe2f7
# 
# 

# ********RoostGPT********
Feature: Account Status By Account ID

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Retrieve account details with valid bearer token
  * def headers = function() { return { 'Authorization': '#(authValue)', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254',
                      'x-fapi-interaction-id': '#(interactionId)', 'Accept-Language': '#(lang)' }; }
  * configure headers = headers()
  Given path 'aisp/accounts', '#(accountId)'
  When method get
  Then status 200
  And match response.headers['Content-Type'] == 'application/json'
  And match response.data.account[*].accountId == '#(accountId)'
  
Examples:
| authValue                             | accountId          | interactionId              | lang   |
| 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'  | 'EcU-RcLMV6mZzDu8vrfEFg' | 'd3cb4575-60bf-40b4-9c97-637efd78977d' | 'en-US'  |
| 'Bearer UbGDbVcFVVfE-ngpjj8KaH5wrEfg'  | 'ThR-RpLMV5lZzDu8vrfEFg' | 'e3db4575-70bf-40b4-9c97-637efd78977d' | 'zh-HK'  |
| 'Bearer LbGDbcFVVfE-ngpjj8KaH5wrEfg'  | 'VhV-RvLMV7nZzDu8vrfEGf' | 'f2ca3475-80bf-40b4-9c97-637efd78977d' | 'zh-CN'  |
