# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/accounts/{accountId}_get for http method type GET 
# RoostTestHash=1645afe2f7
# 
# 

# ********RoostGPT********
Feature: Test accountStatusbyAccountId endpoint

  Background:
    * def urlBase = (karate.properties['url.base']) ? karate.properties['url.base'] :  'http://localhost:4010'
    * url urlBase
    * def authHeaders = {"Authorization": "#(BASE_TOKEN)"}

  Scenario Outline: Get account status by Account ID success scenario
    Given path 'aisp', 'accounts', '<accountId>'
    And headers authHeaders
    When method get
    Then status 200
    And match header Content-Type == 'application/json'
    And match each response.data.account == {"accountId": '#string', "accountNumber": '#string', "accountType": '#string', "accountSubType": '#string', "productName": '#string', "accountStatus": '#string', "currency": '#string'}
    And match response.links.self == '#string'

    Examples:
      | read('aisp_accounts_accountId_get.csv') |

  Scenario Outline: Negative scenario
    Given path 'aisp', 'accounts', '<accountId>'
    And headers authHeaders
    When method get
    Then status 400
    And match header Content-Type == 'application/json'
    And match response.code == 400
    And match response.message == 'Bad Request'
    And match each response.errors == {"code": '#string', "causes": '#string'}

    Examples:
      | read('aisp_accounts_accountId_get.csv') |
