# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_delete for http method type DELETE 
# RoostTestHash=460872f4ab
# 
# 

# ********RoostGPT********
Feature: Account Consent Setup Validations

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase + '/aisp/account-consents'
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def headers = { 'Authorization': '#(AUTH_TOKEN)', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': '1234', 'accept': 'application/json' }

  Scenario Outline: Test GET method on /aisp/account-consents/<consentId> with valid input
    Given path '/' + consentId
    And headers headers
    When method get
    Then status 204
    And match responseHeaders contains { 'x-fapi-interaction-id': '#string' }

    Examples:
      | read('aisp_account-consents_consentId_delete.csv') |

  Scenario Outline: Test GET method on /aisp/account-consents/<consentId> with invalid input
    Given path '/' + consentId
    And headers headers
    When method get
    Then match responseStatus in [400, 401, 403, 405, 406, 429, 500, 503, 504]
    And match response contains { 'id': '#string', 'errors': '#[]' }
    And match each response.errors contains { 'code' : '#string', 'cause': '#string'}

    Examples:
      | read('aisp_account-consents_consentId_delete.csv') |
