# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /aisp/account-consents/{consentId}_get for http method type GET 
# RoostTestHash=8f01df3f76
# 
# 

# ********RoostGPT********
Feature: API Feature

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def token = karate.properties['AUTH_TOKEN'] || karate.get('token', 'ABC123')
    * configure headers = {Header1: '#(token)', Header2: '#(token)'}

Scenario Outline: Verify GET Method
    * path '/aisp/account-consents', '<consentId>'
    * method get
    * status 200
    * match response contains {data: '#notnull'}

    Examples:
    | consentId |
    | '7404e99b-1a4d-4b08-b441-c327661527f0' |

Scenario: Validate Bad Request Error for GET  
    * path '/aisp/account-consents', '7404e99b-1a4d-4b08-b441-c327661527f0'
    * method get
    * status 400
    * match response contains {id: '#notnull', errors: '#notnull'}

Scenario: Validate Unauthorized Error for GET  
    * path '/aisp/account-consents', '7404e99b-1a4d-4b08-b441-c327661527f0'
    * method get
    * status 401
    * match response == {}

Scenario: Validate Forbidden Error for GET  
    * path '/aisp/account-consents', '7404e99b-1a4d-4b08-b441-c327661527f0'
    * method get
    * status 403
    * match response == {}

Scenario: Validate Method Not Allowed error for POST
    * path '/aisp/account-consents', '7404e99b-1a4d-4b08-b441-c327661527f0'
    * method post
    * status 405
    * match response contains {id: '#notnull', errors: '#notnull'}
