# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=38fc35e650
# 
# 

# ********RoostGPT********
Feature: Notification Event Endpoints

Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * configure headers = { Authorization: '#(bearerAuthSession)', 'Content-Type': 'application/json',
                            'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC',
                            'x-fapi-customer-ip-address': '169.254.169.254',
                            'x-fapi-interaction-id': 'someID',
                            'Accept-Language': 'en-HK' }

Scenario Outline: Test Notification Event
    Given path '/events'
    And request {"returnImmediately": <returnImmediately>, "maxEvents": <maxEvents>}
    When method post
    Then status <status>

Examples:
    | returnImmediately | maxEvents | status |
    | true              | 5         | 201    |
    | false             | 5         | 201    |
    | false             | null      | 400    |

Scenario Outline: Verifying Error Codes for Invalid Scenarios
    Given path '/events'
    And request {"returnImmediately": <returnImmediately>, "maxEvents": <maxEvents>}
    When method post
    Then status <status>
    And match response == { "errors" : [ { "type": '#string', "title": '#string', "status": '#number', "detail": '#string', "instance": '#string'} ] }

Examples:
    | returnImmediately | maxEvents | status |
    | ''                | 5         | 400    |
    | true              | ''        | 400    |
