# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=38fc35e650
# 
# 

# ********RoostGPT********
Feature: Notification event endpoints API test

  Background:
    * def urlBase = karate.properties['url.base'] || 'http://localhost:4010'
    * url urlBase
    * def bearerToken = karate.properties['AUTH_TOKEN']
    * configure headers = {Authorization: '#(bearerToken)', 'Content-Type': 'application/json', 'x-fapi-auth-date': 'Sun, 10 Sep 2017 19:43:31 UTC', 'x-fapi-customer-ip-address': '169.254.169.254', 'x-fapi-interaction-id': '0', Accept-Language: 'en-HK'}

  Scenario Outline: Validate the /events API with POST
    Given path '/events'
    And request <requestPayload>
    When method post
    Then status <status>
    And match $ == <responsePayload>
    And match responseHeaders['Content-Type']=='application/json'

    Examples:
      | read('events_post.csv') |
