# ********RoostGPT********

# Test generated by RoostGPT for test HSBC-HK-Market-Api-Spec using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /events_post for http method type POST 
# RoostTestHash=38fc35e650
# 
# 

# ********RoostGPT********
Feature: Testing /events API endpoint

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = { Authorization: '#(authToken)', 'Content-Type': 'application/json' }

Scenario Outline: Call the /events endpoint with valid request body and check the HTTP status code and response
  Given path '/events'
  And headers headers
  And request <requestBody>
  When method post
  Then status <statusCode>
  And match response == <responseBody>

  Examples: 
    | requestBody                                                             | statusCode | responseBody                              |
    | { "ack": ["ack1", "ack2"], "returnImmediately": true, "maxEvents": 2 }  | 201         | { "sets": {}, "moreAvailable": true }    |
    | { "ack": ["ack3", "ack4"], "returnImmediately": true, "maxEvents": 2 }  | 400         | { "errors": {"code":"OB.Field.Missing"} } |
    | { "ack": ["ack5", "ack6"], "returnImmediately": false, "maxEvents": 1 } | 500         | { "errors": {"code":"OB.Field.Invalid"} } |
    | { "ack": [], "returnImmediately": true, "maxEvents": 0 }                | 201         | { "sets": {}, "moreAvailable": false }   |

Scenario Outline: Call the /events endpoint without proper authorization and check the HTTP status code
  Given path '/events'
  And request <requestBody>
  When method post
  Then status 401

  Examples: 
    | requestBody |
    | { "ack": ["ack1", "ack2"], "returnImmediately": true, "maxEvents": 2 } |
    | { "ack": ["ack3", "ack4"], "returnImmediately": true, "maxEvents": 2 } |
    | { "ack": ["ack5", "ack6"], "returnImmediately": false, "maxEvents": 1 } |
    | { "ack": [], "returnImmediately": true, "maxEvents": 0 } |

Scenario Outline: Call the /events endpoint with invalid methods and check the HTTP status code
  Given path '/events'
  And headers headers
  When method <invalidMethod>
  Then status 405

  Examples: 
    | invalidMethod |
    | get           |
    | put           |
    | delete        |
