# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureate

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def LaureateID = 456

  Scenario: Successful operation using PATH method to get Laureate Information
    Given path '2.1/laureate', LaureateID
    When method get
    Then status 200
    And match response ==
      """
      {
        "laureate": {
          "id": 456,
          "laureateIfPerson": {
            "knownName": {
                "en": "English",
                "se": "Svenska",
                "no": "Norsk"
            },
            "gender":"female"
         },
         "laureateIfOrg": {
          },
        }
      }
      """

  Scenario Outline: Failed operations
    Given path '2.1/laureate', invalidLaureateID
    When method get
    Then status <statusCode>
    And match response ==
      """
      {
        "code": "<statusCode>",
        "message": "There is not Laureate born that date"
      }
      """

    Examples:
      | invalidLaureateID | statusCode |
      | 'invalidID'       | 400        |
      | 'nonexistent'     | 404        |
      | 'nonnumeric'      | 422        |
