# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
  Feature: Validate the laureates API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase

  Scenario Outline: Laureates search with valid parameters
    Given path '/2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param ID = <ID>
    When method GET
    Then status 200

    Examples:
      | offset | limit | sort   | ID |
      |      1 |     5 | 'asc'  |  1 |
      |      2 |    10 | 'desc' |  2 |
      |      3 |    15 | 'asc'  |  3 |

  
  Scenario Outline: Laureates search with invalid parameters
    Given path '/2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param ID = <ID>
    When method GET
    Then match response.code ==  400
    And match response.message == 'There is not Laureate born that date'

    Examples:
      | offset | limit | sort   | ID |
      |     -1 |     5 | 'asc'  |  1 |
      |      2 |   -10 | 'desc' |  2 |
      |      3 |     0 | 'asc'  |  3 |
