# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=99e96e3191
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event

  Background:
    * url karate.properties['url.base'] || 'http://localhost:4010'
    * configure headers = { 'Authorization': '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Verify the endpoint for Product Order Information Required Event
    Given path '/listener/productOrderInformationRequiredEvent'
    And request <requestBody>
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |
