# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=10f12a7f6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def AUTH_TOKEN = karate.properties['AUTH_TOKEN']
    * def requestHeaders = { 'Authorization': '#(' + AUTH_TOKEN + ')', 'Content-Type': 'application/json' }

  Scenario Outline: Verify the response code and body for the given endpoint with valid request body
    Given path '/listener/productOrderCreateEvent'
    And headers requestHeaders
    And request <requestBody>
    When method post
    Then status <statusCode>
    And match response == '#(^responseBody$)'

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario Outline: Verify the response code for the given endpoint with invalid request method
    Given path '/listener/productOrderCreateEvent'
    And headers requestHeaders
    When method <requestMethod>
    Then status 405

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |

  Scenario: Verify the response code for the given endpoint without authorization header
    Given path '/listener/productOrderCreateEvent'
    And request { "notification": { "date": "2021-06-05T20:23:29-03:00", "order": { "id": "20230315000001", "associatedDocument": "VTT001", "correlationOrder": "10" } } }
    When method post
    Then status 401
