# ********RoostGPT********

# Test generated by RoostGPT for test ProductOrderingKarate using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /listener/productOrderInformationRequiredEvent_post for http method type POST 
# RoostTestHash=99e96e3191
# 
# 

# ********RoostGPT********
Feature: Product Order Information Required Event

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Notify product order information required event
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = authToken
    And request
      """
      {
        "notification": {
          "date": "<date>",
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "order": {
            "id": "<orderId>",
            "correlationOrder": "<correlationOrder>",
            "associatedDocument": "<associatedDocument>",
            "issue": {
              "code": "<issueCode>",
              "description": "<issueDescription>",
              "type": "<issueType>",
              "observation": "<issueObservation>",
              "updateDate": "<issueUpdateDate>",
              "action": "<issueAction>",
              "task": "<issueTask>",
              "fieldActivity": "<issueFieldActivity>",
              "reason": "<issueReason>"
            },
            "type": "<orderType>",
            "code": "<notificationCode>",
            "description": "<notificationDescription>",
            "lostEquipment": "<lostEquipment>",
            "resource": {
              "gponAccess": "<gponAccess>",
              "devices": {
                "device": [
                  {
                    "category": "<deviceCategory>",
                    "type": "<deviceType>",
                    "description": "<deviceDescription>",
                    "state": "<deviceState>",
                    "usageState": "<deviceUsageState>",
                    "startOperatingDate": "<deviceStartOperatingDate>",
                    "resourceCharacteristic": [
                      {
                        "name": "<resourceCharacteristicName>",
                        "value": "<resourceCharacteristicValue>"
                      }
                    ]
                  }
                ]
              },
              "fiberPath": {
                "items": {
                  "item": [
                    {
                      "name": "<fiberPathItemName>",
                      "value": "<fiberPathItemValue>"
                    }
                  ]
                }
              }
            }
          }
        }
      }
      """
    When method POST
    Then status 204
    And match header Content-Type contains 'application/json'

    Examples:
      | read('listener_productOrderInformationRequiredEvent_post.csv') |

  Scenario: Notify product order information required event with invalid request
    Given path '/listener/productOrderInformationRequiredEvent'
    And header Authorization = authToken
    And request
      """
      {}
      """
    When method POST
    Then status 400
    And match header Content-Type contains 'application/json'
    And match response contains 'BadRequest'

  Scenario: Notify product order information required event with unauthorized access
    Given path '/listener/productOrderInformationRequiredEvent'
    And request
      """
      {}
      """
    When method POST
    Then status 401
    And match header Content-Type contains 'application/json'
    And match response contains 'Unauthorized'
