# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase

  Scenario Outline: Obtain information about one specific Nobel Prize
    Given path '/2.1/nobelPrize/', '<category>', '<year>'
    When method get
    Then status 200
    And match response == {"nobelPrize": '#object'}
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.topMotivation.en == '#string'

    Examples:
      | category | year |
      | 'lit'    | 2000 |
      | 'peace'  | 2012 |
      | 'med'    | 1992 |

  Scenario: Invalid Category
    Given path '/2.1/nobelPrize/', 'invalid', 2000
    When method get
    Then status 400
    And match response.code == '400'
    And match response.message == 'Bad request. The request could not be understood by the server due to malformed syntax, modifications needed.'

  Scenario: Invalid Year
    Given path '/2.1/nobelPrize/', 'lit', 1200
    When method get
    Then status 400
    And match response.code == '400'
    And match response.message == 'Bad request. The request could not be understood by the server due to malformed syntax, modifications needed.'
