# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Testing

Background:
* def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')  
* url urlBase

Scenario: Test all Nobel Prizes API
  Given path '/2.1/nobelPrizes'
  And params { "offset" : "#(offset)", "limit" : "#(limit)", 
               "sort" : "#(sort)", "nobelPrizeYear" : "#(nobelPrizeYear)", 
               "yearTo" : "#(yearTo)", "nobelPrizeCategory" : "#(nobelPrizeCategory)", 
               "format" : "#(format)", "csvLang" : "#(csvLang)" }
  When method get
  Then status 200
  And match $ contains { nobelPrizes: '#[] _'}
  And match each $.nobelPrizes contains { awardYear:'#number', prizeAmount:'#number' }

  Examples:
    | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
    | 1      | 10    | 'asc' | 2000           | 2010   | 'phi'              | 'json' | 'es'    |
    | 0      | 5     | 'desc'| 1990           | 2000   | 'che'              | 'json' | 'en'    |

Scenario: Test Nobel Prizes API with incorrect offset and limit
  Given path '/2.1/nobelPrizes'
  And params { "offset" : "#(offset)", "limit" : "#(limit)" }
  When method get
  Then status 400

  Examples:
    | offset | limit |
    | -1     | 10    |
    | 1      | 0     |

Scenario: Test Nobel Prizes API for unavailable resource
  Given path '/2.1/nobelPrizes'
  And params { "nobelPrizeYear" : "#(nobelPrizeYear)" }
  When method get
  Then status 404

  Examples:
    | nobelPrizeYear | 
    | 1899           |

Scenario: Test Nobel Prizes API for invalid parameters
  Given path '/2.1/nobelPrizes'
  And params { "nobelPrizeYear" : "#(nobelPrizeYear)" }
  When method get
  Then status 422

  Examples:
    | nobelPrizeYear |
    | 'abcd'         |
