# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Information API feature testing

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Verify successful retrieval of Nobel Prize info by category and year
  Given path '2.1', 'nobelPrize', '<category>', '<year>'
  When method get
  Then status 200
  And match response.nobelPrize.awardYear == '<year>'
  And match response.nobelPrize.category.en == '<category>'
  And response.nobelPrize.categoryFullName.en contains '<category>'
  And response.nobelPrize.dateAwarded != null
  And response.nobelPrize.prizeAmount == '#integer'
  And response.nobelPrize.prizeAmountAdjusted == '#integer'
  And response.nobelPrize.topMotivation.en != null
  And response.nobelPrize.laureates[*].id != null
  Examples:
    | category | year |
    | 'chemistry' | 2019 |
    | 'literature' | 2018 |
    | 'physics' | 2020 |

Scenario Outline: Verify unsuccessful retrieval of Nobel Prize info due to incorrect category and year
  Given path '2.1', 'nobelPrize', '<category>', '<year>'
  When method get
  Then status <statusCode>
  And match response.code == '<statusCode>'
  Examples:
    | category | year | statusCode |
    | 'invalidCategory' | 2025 | 400 |
    | 'chemistry' | 1899 | 422 |
    | 'nonexist' | 1900 | 404 |

