# ********RoostGPT********

# Test generated by RoostGPT for test karateNobel using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Testing

Background:
  * configure headers = { Authorization: '#(authToken)' }
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase

Scenario Outline: Verify the Nobel Prizes API

  # Sending the request
  Given path '/2.1/nobelPrizes'
  And param offset = '<offset>'
  And param limit = '<limit>'
  And param sort = '<sort>'
  And param nobelPrizeYear = '<nobelPrizeYear>'
  And param yearTo = '<yearTo>'
  And param nobelPrizeCategory = '<nobelPrizeCategory>'
  And param format = '<format>'
  And param csvLang = '<csvLang>'
  When method get
  Then status 200
  And match response is { nobelPrizes: '#array' }
  And match each response.nobelPrizes contains { 
    awardYear: '#number',
    dateAwarded: '#string',
    prizeAmount: '#number',
    prizeAmountAdjusted: '#number'
  }

  # Checking data types
  And match response.nobelPrizes[*].awardYear contains only '#? _.isNumber' 
  And match response.nobelPrizes[*].dateAwarded contains only '#? _.isString' 
  And match response.nobelPrizes[*].prizeAmount contains only '#? _.isNumber' 
  And match response.nobelPrizes[*].prizeAmountAdjusted contains only '#? _.isNumber' 

Examples:
  | offset | limit | sort  | nobelPrizeYear | yearTo | nobelPrizeCategory | format | csvLang |
  |   1    |   10  | 'asc' |      2020      |  2021  |    'eco'           | 'json' |  'en'   |
