# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=d2b09bfc44
# 
# 

# ********RoostGPT********
Feature: Product Order API feature

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test Product Order API endpoint with different response codes
    Given path '/productOrder'
    And request {}
    When method post
    Then status <statusCode>
    And match response == {type: '#string', message: '#string', code: '#string'}
    And match responseHeaders == {headers: '#notnull'}

    Examples:
      | read('productOrder_post.csv') |

  Scenario: Test Product Order API endpoint with 201 response code
    Given path '/productOrder'
    And request {}
    When method post
    Then status 201
    And match response == {control: '#object', order: '#object'}
    And match response.control == {type: '#string', message: '#string', code: '#string'}
    And match response.order == {id: '#string'}
    And match responseHeaders == {headers: '#notnull'}
