# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=a40197b7fc
# 
# 

# ********RoostGPT********
Feature: Product Order API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test product order API with valid parameters
    Given path 'productOrder', '<orderId>'
    And request
      """
      { 
        "order": #(order) 
      }
      """
    When method patch
    Then match responseStatus == <statusCode>
    And match responseHeaders == {}
    And match response == { "type": '#string', "message": '#string', "code": '#string' }

    Examples:
      | read('productOrder_order.Id_patch.csv') |
