# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/serviceTestResultEvent_post for http method type POST 
# RoostTestHash=5f2c54c9f8
# 
# 

# ********RoostGPT********
Feature: Listener Service Test Result Event API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)' }

  Scenario Outline: Validate POST /listener/serviceTestResultEvent API
    Given path '/listener/serviceTestResultEvent'
    And request
      """
      {
        "notification": {
          "customer": {
            "subscriberId": "<subscriberId>"
          },
          "serviceTest": {
            "id": "<id>",
            "type": "<type>",
            "startDate": "<startDate>",
            "endDate": "<endDate>",
            "state": "<state>",
            "diagnostic": {},
            "hintOperations": {},
            "result": {}
          }
        }
      }
      """
    When method post
    Then status <statusCode>

    Examples:
      | read('listener_serviceTestResultEvent_post.csv') |
