# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/serviceTestResultEvent_post for http method type POST 
# RoostTestHash=5f2c54c9f8
# 
# 

# ********RoostGPT********
Feature: Listener Service Test Result Event API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test Listener Service Test Result Event API
    Given path '/listener/serviceTestResultEvent'
    And request
      """
      { 
        'notification': { 
          'customer': { 
            'subscriberId': '<subscriberId>' 
          }, 
          'serviceTest': { 
            'id': '<id>', 
            'type': '<type>', 
            'startDate': '<startDate>', 
            'endDate': '<endDate>', 
            'state': '<state>', 
            'diagnostic': {}, 
            'hintOperations': {}, 
            'result': {} 
          } 
        } 
      }
      """
    When method post
    Then match responseStatus == <responseStatus>
    And match responseHeaders == <responseHeaders>

    Examples:
      | read('listener_serviceTestResultEvent_post.csv') |
