# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /serviceTest_post for http method type POST 
# RoostTestHash=a0badb7b73
# 
# 

# ********RoostGPT********
Scenario Outline: Testing Service Test API with different request payloads
  Given path '/serviceTest'
  And request <requestBody
  When method post
  Then status <statusCode>
  And match response == <responseBody

  Examples:
    | requestBody                                                                                                   | statusCode | responseBody                                                                                                                                    |
    | { "serviceTest": { "type": "diagnostic", "customer": { "subscriberId": "SVTAL001" } } }                       |        200 | { "control": { "type": "S", "code": "200", "message": "OK" }, "serviceTest": { "id": "#string" } }                                              |
    | { "serviceTest": { "type": "wrongType", "customer": { "subscriberId": "SVTAL001" } } }                        |        400 | { "control": { "type": "E", "code": "400", "message": "Bad Request" } }                                                                         |
