# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=f9512deb98
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def auth = karate.properties['AUTH_TOKEN']
    * header Authorization = auth

  Scenario Outline: Validate Cancel Product Order By Id API
    Given path '/cancelProductOrder', orderId
    And def requestBody = { order:{ associatedDocument: '#(associatedDocument)', customer:{ subscriberId: '#(subscriberId)' }}}
    And request requestBody
    When method post
    Then match responseStatus == statusCode
    And match response.control.type == responseType
    And match response.control.message == responseMessage
    And match response.control.code == responseCode

    Examples:
      | read('cancelProductOrder_order.Id_post.csv') |
