# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /cancelProductOrder/{order.Id}_post for http method type POST 
# RoostTestHash=f9512deb98
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order By Id

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def auth = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }
    * configure headers = auth

  Scenario Outline: Test Cancel Product Order By Id
    Given path '/cancelProductOrder', '<order_id>'
    And request <body>
    When method post
    Then status <status>
    And match response == <response>

    Examples:
      | read('cancelProductOrder_order.Id_post.csv') |
