# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=999efa10b6
# 
# 

# ********RoostGPT********
Feature: Cancel Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { 'Authorization': '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Validate API endpoint for different response status
    Given path '/listener/cancelProductOrderCreateEvent'
    And request <requestBody>
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('listener_cancelProductOrderCreateEvent_post.csv') |
