# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=10f12a7f6a
# 
# 

# ********RoostGPT********
Feature: Product Order Create Event By Client

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * def requestHeaders = { 'Authorization': '#(authToken)' }

  Scenario Outline: Verify Product Order Create Event By Client API
    Given path '/listener/productOrderCreateEvent'
    And headers requestHeaders
    And request <requestBody>
    When method post
    Then status <statusCode>
    And match response == <responseBody>

    Examples:
      | read('listener_productOrderCreateEvent_post.csv') |
