# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderStateChangeEvent_post for http method type POST 
# RoostTestHash=2a8518ba6f
# 
# 

# ********RoostGPT********
Feature: Product Order State Change Event API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'Authorization': '#(authToken)' }

  Scenario Outline: Validate API response for different state change events
    Given path '/listener/productOrderStateChangeEvent'
    And request <requestBody>
    When method post
    Then status <statusCode>
    And match response == '#null'

    Examples:
      | read('listener_productOrderStateChangeEvent_post.csv') |
