# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/cancelProductOrderCreateEvent_post for http method type POST 
# RoostTestHash=999efa10b6
# 
# 

# ********RoostGPT********
' within the feature file. This is unnecessary and not recognized by the parser. The corrected karate tests feature file will look like this:

---ROOST FEATURES START--- 
