# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /listener/productOrderCreateEvent_post for http method type POST 
# RoostTestHash=10f12a7f6a
# 
# 

# ********RoostGPT********
' at the beginning of the feature file. This is not a valid Gherkin syntax and should be removed. The corrected feature file is as follows:

---ROOST FEATURES START--- 
