# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=d2b09bfc44
# 
# 

# ********RoostGPT********
Feature: Testing /productOrder endpoint

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test POST /productOrder endpoint with valid input
    Given path '/productOrder'
    And request <requestBody>
    When method post
    Then status <status>
    And match response == <expectedResponse>

    Examples:
      | read('productOrder_post.csv') |
