# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=a40197b7fc
# 
# 

# ********RoostGPT********
Feature: Product Order API Tests

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test PATCH /productOrder/{order.Id} endpoint
    Given path 'productOrder', '<order.Id>'
    And request
      """
        {
          "order": "#(order)", 
          "order.correlationOrder": "#(order.correlationOrder)", 
          "order.associatedDocument": "#(order.associatedDocument)", 
          "order.associatedDocumentDate": "#(order.associatedDocumentDate)", 
          "order.type": "#(order.type)", 
          "order.infraType": "#(order.infraType)", 
          "order.orderItem": "#(order.orderItem)", 
          "order.task": "#(order.task)", 
          "order.task.description": "#(order.task.description)", 
          "order.task.updateDate": "#(order.task.updateDate)", 
          "order.task.action": "#(order.task.action)"
        }
      """
    When method patch
    Then match responseStatus == <responseStatus>
    And match responseType == <responseType>
    And match responseMessage == <responseMessage>
    And match responseCode == <responseCode>

    Examples:
      | read('productOrder_order.Id_patch.csv') |
