# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder_post for http method type POST 
# RoostTestHash=d2b09bfc44
# 
# 

# ********RoostGPT********
Feature: Test /productOrder API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test POST /productOrder API and validate the response status and body with various inputs
    Given I set path to '/productOrder'
    And I set request body to <requestBody>
    When I send a POST request
    Then I expect the response status to be <responseStatus>
    And I expect the response body to be <responseBody>

    Examples:
      | read('productOrder_post.csv') |
