# ********RoostGPT********

# Test generated by RoostGPT for test karateTest-product using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /productOrder/{order.Id}_patch for http method type PATCH 
# RoostTestHash=a40197b7fc
# 
# 

# ********RoostGPT********
Feature: Product Order API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase

  Scenario Outline: Test PATCH /productOrder/{orderId} endpoint
    Given path 'productOrder', '<orderId>'
    And request
      """
      {
        "order": {
          "correlationOrder": "example correlationOrder",
          "associatedDocument": "example associatedDocument",
          "associatedDocumentDate": "2021-10-01T00:00:00Z",
          "type": "example type",
          "infraType": "example infraType",
          "orderItem": ["example item 1", "example item 2"],
          "task": {
            "description": "example task description",
            "updateDate": "2021-10-01T00:00:00Z",
            "action": "example action"
          }
        }
      }
      """
    When method patch
    Then status <status_code>
    And match response == '#string'

    Examples:
      | read('productOrder_order.Id_patch.csv') |
